pipeline:
  name: Remote 1
  identifier: Remote
  projectIdentifier: Pankaj
  orgIdentifier: default
  tags: {}
  stages:
    - parallel:
        - stage:
            name: S1
            identifier: S1
            tags: {}
            template:
              templateRef: Pipeline_Stage_Template_Path_Auto
              versionLabel: V1
              gitBranch: main
              templateInputs:
                type: Custom
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: ShellScript_1
                          type: ShellScript
                          timeout: <+input>
        - stage:
            name: S2
            identifier: S2
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: ShellScript
                      name: ShellScript_1
                      identifier: ShellScript_1
                      spec:
                        shell: Bash
                        onDelegate: true
                        source:
                          type: Inline
                          spec:
                            script: echo "Stage 2"
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
            tags: {}
        - stage:
            name: S3
            identifier: S3
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: ShellScript
                      name: ShellScript_1
                      identifier: ShellScript_1
                      spec:
                        shell: Bash
                        onDelegate: true
                        source:
                          type: Inline
                          spec:
                            script: echo "Stage 3"
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
            tags: {}
    - stage:
        name: S4
        identifier: S4
        tags: {}
        template:
          templateRef: Shell_S4
          versionLabel: V1
          gitBranch: main
          templateInputs:
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      identifier: TerraformRollback_1
                      type: TerraformRollback
                      spec:
                        provisionerIdentifier: <+input>
                        delegateSelectors: <+input>
                  - stepGroup:
                      identifier: S2
                      steps:
                        - parallel:
                            - step:
                                identifier: TerraformRollback_2
                                type: TerraformRollback
                                spec:
                                  provisionerIdentifier: <+input>
                                  delegateSelectors: <+input>
                            - step:
                                identifier: TerraformRollback_3
                                type: TerraformRollback
                                spec:
                                  provisionerIdentifier: <+input>
                      delegateSelectors: <+input>
  allowStageExecutions: true
