pipeline:
  name: Remote
  identifier: Remote
  projectIdentifier: Pankaj
  orgIdentifier: default
  tags: {}
  stages:
    - parallel:
        - stage:
            name: S1
            identifier: S1
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: ShellScript
                      name: ShellScript_1
                      identifier: ShellScript_1
                      spec:
                        shell: Bash
                        onDelegate: true
                        source:
                          type: Inline
                          spec:
                            script: echo "Main Stage S1"
                        environmentVariables: []
                        outputVariables: []
                      timeout: <+input>
            tags: {}
        - stage:
            name: S2
            identifier: S2
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: ShellScript
                      name: ShellScript_1
                      identifier: ShellScript_1
                      spec:
                        shell: Bash
                        onDelegate: true
                        source:
                          type: Inline
                          spec:
                            script: echo "Stage 2"
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
            tags: {}
        - stage:
            name: S3
            identifier: S3
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: ShellScript
                      name: ShellScript_1
                      identifier: ShellScript_1
                      spec:
                        shell: Bash
                        onDelegate: true
                        source:
                          type: Inline
                          spec:
                            script: echo "Stage 3"
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
            tags: {}
    - stage:
        name: S4
        identifier: S4
        tags: {}
        template:
          templateRef: Shell_S4
          versionLabel: V1
          gitBranch: main
  allowStageExecutions: true
