pipeline:
  name: Non Main Branch
  identifier: Non_Manin_Branch
  projectIdentifier: Pankaj
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: S1
        identifier: S1_1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: Echo Stage 1
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
    - stage:
        name: S2
        identifier: S2
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: Echo Stage 2
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
    - stage:
        name: S3
        identifier: S3
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: Echo Stage 3
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
    - stage:
        name: S4
        identifier: S4
        template:
          templateRef: Shell_Script_Template
          versionLabel: V1
  allowStageExecutions: true
