pipeline:
  name: Account Level Connector For GitX
  identifier: Account_Level_Connector_For_GitX
  projectIdentifier: Pankaj
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: S1
        identifier: S1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo Hello
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
        tags: {}
