pipeline:
  name: Demo Parent Pipeline
  identifier: Demo_Parent_Pipeline
  projectIdentifier: Pankaj
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: S1
        identifier: S1
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: Remote_Default_branch
          project: Pankaj
          inputs:
            identifier: Remote_Default_branch
            stages:
              - stage:
                  identifier: S1
                  type: Custom
                  spec:
                    execution:
                      steps:
                        - step:
                            identifier: ShellScript_1
                            type: ShellScript
                            timeout: <+input>
              - stage:
                  identifier: S2
                  type: Custom
                  spec:
                    execution:
                      steps:
                        - step:
                            identifier: ShellScript_1
                            type: ShellScript
                            timeout: <+input>
          gitBranch: main-patch-22-Jan
