pipeline:
  name: "Deploy Path Auto Creation "
  identifier: Deploy_Path_Auto_Creation
  projectIdentifier: Pankaj
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: S1
        identifier: S1
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: Pipeline_Svc_Auto_Path
          environment:
            environmentRef: Pipeline_Env_Path_Auto_Creation
            gitBranch: main
            deployToAll: false
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  template:
                    templateRef: Rolling_Pipeline_Step_Template_Path_Auto
                    versionLabel: V1
                    gitBranch: main
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
