pipeline:
  name: Oauth Test 2
  identifier: Oauth_Test_2
  tags: {}
  template:
    templateRef: Shell_Pipeline
    versionLabel: V1
    templateInputs:
      stages:
        - stage:
            identifier: S1
            template:
              templateInputs:
                type: Custom
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: ShellScript_1
                          template:
                            templateInputs:
                              type: ShellScript
                              timeout: <+input>
  projectIdentifier: Pankaj
  orgIdentifier: default
