pipeline:
  name: Oauth test 3
  identifier: Oauth_test_3
  tags: {}
  template:
    templateRef: Shell_Pipeline
    versionLabel: V1
    templateInputs:
      stages:
        - stage:
            identifier: S1
            template:
              templateInputs:
                type: Custom
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: ShellScript_1
                          template:
                            templateInputs:
                              type: ShellScript
                              timeout: 10m
  projectIdentifier: Pankaj
  orgIdentifier: default
