pipeline:
  name: Oauth Test 2
  identifier: Oauth_Test_2
  tags: {}
  template:
    templateRef: Shell_Pipeline
    versionLabel: V1
    templateInputs:
      stages:
        - stage:
            identifier: S1
            template:
              templateInputs:
                type: Custom
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: ShellScript_1
                          template:
                            templateInputs:
                              type: ShellScript
                              timeout: <+input>
        - stage:
            identifier: S2
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      identifier: ShellScript_1
                      type: ShellScript
                      timeout: <+input>
        - stage:
            identifier: S3
            type: CI
            spec:
              execution:
                steps:
                  - step:
                      identifier: Run_1
                      type: Run
                      spec:
                        registryRef: <+input>
                        image: <+input>
      properties:
        ci:
          codebase:
            repoName: <+input>
            build: <+input>
  projectIdentifier: Pankaj
  orgIdentifier: default
