pipeline:
  name: "Pipeline Path Auto Creation "
  identifier: Pipeline_Path_Auto_Creation
  tags: {}
  projectIdentifier: Pankaj
  orgIdentifier: default
  stages:
    - stage:
        name: S1
        identifier: S1
        tags: {}
        template:
          templateRef: Pipeline_Stage_Template_Path_Auto
          versionLabel: V1
          templateInputs:
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      identifier: ShellScript_1
                      type: ShellScript
                      timeout: <+input>
            variables:
              - name: Test
                type: String
                value: <+input>.allowedValues(a,s,d,f)
              - name: Test2
                type: String
                value: <+input>
    - stage:
        name: S2
        identifier: S2
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo S2
                    environmentVariables: []
                    outputVariables:
                      - name: Test
                        type: String
                        value: <+input>
                  timeout: 10m
        tags: {}
