pipeline:
  name: Remote Default branch
  identifier: Remote_Default_branch
  projectIdentifier: Pankaj
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: S1
        identifier: S1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo S1
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
        tags: {}
    - stage:
        name: S2
        identifier: S2
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: Remote_Child_Pipeline
          project: Pankaj
          gitBranch: test-1
          inputs:
            identifier: Remote_Child_Pipeline
            stages:
              - stage:
                  identifier: S1
                  type: Custom
                  spec:
                    execution:
                      steps:
                        - step:
                            identifier: ShellScript_1
                            type: ShellScript
                            timeout: <+input>
